# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minidrone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minidrone.proto',
  package='minidrone',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fminidrone.proto\x12\tminidrone\"\x15\n\x04Test\x12\r\n\x05value\x18\x01 \x01(\x05\"1\n\x10MinidroneMessage\x12\x1d\n\x04test\x18\x01 \x01(\x0b\x32\x0f.minidrone.Testb\x06proto3')
)




_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='minidrone.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='minidrone.Test.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=51,
)


_MINIDRONEMESSAGE = _descriptor.Descriptor(
  name='MinidroneMessage',
  full_name='minidrone.MinidroneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test', full_name='minidrone.MinidroneMessage.test', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=102,
)

_MINIDRONEMESSAGE.fields_by_name['test'].message_type = _TEST
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['MinidroneMessage'] = _MINIDRONEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'minidrone_pb2'
  # @@protoc_insertion_point(class_scope:minidrone.Test)
  ))
_sym_db.RegisterMessage(Test)

MinidroneMessage = _reflection.GeneratedProtocolMessageType('MinidroneMessage', (_message.Message,), dict(
  DESCRIPTOR = _MINIDRONEMESSAGE,
  __module__ = 'minidrone_pb2'
  # @@protoc_insertion_point(class_scope:minidrone.MinidroneMessage)
  ))
_sym_db.RegisterMessage(MinidroneMessage)


# @@protoc_insertion_point(module_scope)
