data:
  path: /home/jetson03/mcav/catkin_ws/src/minidrone/mini_ui/data/
  logo: /home/jetson03/mcav/catkin_ws/src/minidrone/mini_ui/src/logo.png

nodes:
  # manual_control: 
  #   name: Manual Control
  #   launch: /home/jetson03/mcav/catkin_ws/src/minidrone/control/launch/manual_control.launch
  jetson_cameras:
    name: Jetson Cameras
    launch: /home/jetson03/mcav/catkin_ws/src/minidrone/mini_ui/launch/mini_ui_cams.launch