# mini config 
data:
  path: /home/jetson03/mcav/catkin_ws/src/minidrone/mini_tools/data/
  logo: /home/jetson03/mcav/catkin_ws/src/minidrone/mini_tools/src/logo.png

nodes:
  manual_control: 
    name: Manual Control
    launch: /home/jetson03/mcav/catkin_ws/src/minidrone/control/launch/manual_control.launch
  jetson_cameras:
    name: Jetson Cameras
    launch: /home/jetson03/mcav/catkin_ws/src/minidrone/mini_tools/launch/mini_ui_cams.launch

required_nodes: ["jetbot_camera_0", "jetbot_camera_1", "web_video_server", 
                  "mini_ui", "recorder", "joystick_twist_node", "joy_node", 
                  "twist_mux", "emergency_brake", "rplidar_node"]

record:
  sim: False
  use_sync: False
  topics: {camera: /jetbot_camera/0/compressed, 
            imu: /imu, 
            gps: /gps,
            twist: /twist_mux/cmd_vel,
            odom: None, 
            status: None,
            manual: None}
extract:
  topics: ["/jetbot_camera/0/compressed", "/imu", "/gps"]