
# sim config
data:
  path: /home/patrick/mcav/catkin_ws/src/minidrone/mini_tools/data/
  logo: /home/patrick/mcav/catkin_ws/src/minidrone/mini_tools/src/logo.png

nodes:
  carla_simulator:
    name: CARLA Simulator
    launch: /home/patrick/mcav/catkin_ws/src/minidrone/mini_tools/launch/mini_ui_sim.launch

required_nodes: ["carla_ros_bridge", "carla_manual_control_hero", "carla_autopilot", "web_video_server", 
                  "mini_ui", "recorder", "compressed_transport_0", "compressed_transport_1"]

record:
  sim: True
  use_sync: True
  topics: {camera: /carla/hero/camera/rgb/front/image_color/compressed, 
            imu: /carla/hero/imu/default, 
            gps: /carla/hero/gnss/default/fix,
            twist: /carla/hero/twist_cmd,
            odom: /carla/hero/odometry, 
            status: /carla/hero/vehicle_status} 
extract:
  topics: ["/carla/hero/camera/rgb/front/image_color/compressed", 
          "/carla/hero/imu/default", 
          "/carla/hero/gnss/default/fix", 
          "/carla/hero/vehicle_status", 
          "/carla/hero/odometry"]

  
