
# sim
data:
  path: /home/patrick/mcav/catkin_ws/src/minidrone/mini_tools/data/
  logo: /home/patrick/mcav/catkin_ws/src/minidrone/mini_tools/src/logo.png

nodes:
  jetson_cameras:
    name: CARLA Simulator
    launch: /home/patrick/mcav/catkin_ws/src/minidrone/mini_tools/launch/mini_ui_sim.launch

required_nodes: ["carla_ros_bridge", "web_video_server", 
                  "mini_ui", "recorder", "image_republisher"]

record:
  topics: {camera: /carla/hero/camera/rgb/front/image_color/compressed, 
            imu: /carla/hero/imu/default, 
            gps: /carla/hero/gnss/default/fix,
            twist: /twist_mux/cmd_vel} # TODO: add CarlaEgoVehicleControl / VehicleStatus
  use_sync: True
extract:
  topics: ["/carla/hero/camera/rgb/front/image_color/compressed", "/carla/hero/imu/default", "/carla/hero/gnss/default/fix"]

  
