/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_MINIDRONE_MINIDRONE_PB_H_INCLUDED
#define PB_MINIDRONE_MINIDRONE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _minidrone_MinidroneMessage {
    char dummy_field;
} minidrone_MinidroneMessage;

typedef struct _minidrone_MinidroneMessage_QDES {
    char dummy_field;
} minidrone_MinidroneMessage_QDES;

typedef struct _minidrone_MinidroneMessage_QDES_ComputeUnit {
    float temp;
    float fan_speed;
} minidrone_MinidroneMessage_QDES_ComputeUnit;

typedef struct _minidrone_MinidroneMessage_QDES_BatteryUnit {
    float temp;
    float fan_speed;
    float voltage;
} minidrone_MinidroneMessage_QDES_BatteryUnit;

typedef struct _minidrone_MinidroneMessage_DriveTrain {
    char dummy_field;
} minidrone_MinidroneMessage_DriveTrain;

typedef struct _minidrone_MinidroneMessage_DriveTrain_Servo {
    float angle;
} minidrone_MinidroneMessage_DriveTrain_Servo;

typedef struct _minidrone_MinidroneMessage_DriveTrain_Wheels {
    char dummy_field;
} minidrone_MinidroneMessage_DriveTrain_Wheels;

typedef struct _minidrone_MinidroneMessage_DriveTrain_Wheels_Left {
    float speed;
    pb_callback_t direction;
} minidrone_MinidroneMessage_DriveTrain_Wheels_Left;

typedef struct _minidrone_MinidroneMessage_DriveTrain_Wheels_Right {
    float speed;
    pb_callback_t direction;
} minidrone_MinidroneMessage_DriveTrain_Wheels_Right;

typedef struct _minidrone_MinidroneMessage_TX2 {
    float temp;
} minidrone_MinidroneMessage_TX2;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define minidrone_MinidroneMessage_init_default  {0}
#define minidrone_MinidroneMessage_QDES_init_default {0}
#define minidrone_MinidroneMessage_QDES_ComputeUnit_init_default {0, 0}
#define minidrone_MinidroneMessage_QDES_BatteryUnit_init_default {0, 0, 0}
#define minidrone_MinidroneMessage_DriveTrain_init_default {0}
#define minidrone_MinidroneMessage_DriveTrain_Servo_init_default {0}
#define minidrone_MinidroneMessage_DriveTrain_Wheels_init_default {0}
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_init_default {0, {{NULL}, NULL}}
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_init_default {0, {{NULL}, NULL}}
#define minidrone_MinidroneMessage_TX2_init_default {0}
#define minidrone_MinidroneMessage_init_zero     {0}
#define minidrone_MinidroneMessage_QDES_init_zero {0}
#define minidrone_MinidroneMessage_QDES_ComputeUnit_init_zero {0, 0}
#define minidrone_MinidroneMessage_QDES_BatteryUnit_init_zero {0, 0, 0}
#define minidrone_MinidroneMessage_DriveTrain_init_zero {0}
#define minidrone_MinidroneMessage_DriveTrain_Servo_init_zero {0}
#define minidrone_MinidroneMessage_DriveTrain_Wheels_init_zero {0}
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_init_zero {0, {{NULL}, NULL}}
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_init_zero {0, {{NULL}, NULL}}
#define minidrone_MinidroneMessage_TX2_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define minidrone_MinidroneMessage_QDES_ComputeUnit_temp_tag 1
#define minidrone_MinidroneMessage_QDES_ComputeUnit_fan_speed_tag 2
#define minidrone_MinidroneMessage_QDES_BatteryUnit_temp_tag 1
#define minidrone_MinidroneMessage_QDES_BatteryUnit_fan_speed_tag 2
#define minidrone_MinidroneMessage_QDES_BatteryUnit_voltage_tag 3
#define minidrone_MinidroneMessage_DriveTrain_Servo_angle_tag 1
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_speed_tag 1
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_direction_tag 2
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_speed_tag 1
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_direction_tag 2
#define minidrone_MinidroneMessage_TX2_temp_tag  1

/* Struct field encoding specification for nanopb */
#define minidrone_MinidroneMessage_FIELDLIST(X, a) \

#define minidrone_MinidroneMessage_CALLBACK NULL
#define minidrone_MinidroneMessage_DEFAULT NULL

#define minidrone_MinidroneMessage_QDES_FIELDLIST(X, a) \

#define minidrone_MinidroneMessage_QDES_CALLBACK NULL
#define minidrone_MinidroneMessage_QDES_DEFAULT NULL

#define minidrone_MinidroneMessage_QDES_ComputeUnit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    fan_speed,         2)
#define minidrone_MinidroneMessage_QDES_ComputeUnit_CALLBACK NULL
#define minidrone_MinidroneMessage_QDES_ComputeUnit_DEFAULT NULL

#define minidrone_MinidroneMessage_QDES_BatteryUnit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    fan_speed,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           3)
#define minidrone_MinidroneMessage_QDES_BatteryUnit_CALLBACK NULL
#define minidrone_MinidroneMessage_QDES_BatteryUnit_DEFAULT NULL

#define minidrone_MinidroneMessage_DriveTrain_FIELDLIST(X, a) \

#define minidrone_MinidroneMessage_DriveTrain_CALLBACK NULL
#define minidrone_MinidroneMessage_DriveTrain_DEFAULT NULL

#define minidrone_MinidroneMessage_DriveTrain_Servo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             1)
#define minidrone_MinidroneMessage_DriveTrain_Servo_CALLBACK NULL
#define minidrone_MinidroneMessage_DriveTrain_Servo_DEFAULT NULL

#define minidrone_MinidroneMessage_DriveTrain_Wheels_FIELDLIST(X, a) \

#define minidrone_MinidroneMessage_DriveTrain_Wheels_CALLBACK NULL
#define minidrone_MinidroneMessage_DriveTrain_Wheels_DEFAULT NULL

#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, CALLBACK, SINGULAR, STRING,   direction,         2)
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_CALLBACK pb_default_field_callback
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_DEFAULT NULL

#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, CALLBACK, SINGULAR, STRING,   direction,         2)
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_CALLBACK pb_default_field_callback
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_DEFAULT NULL

#define minidrone_MinidroneMessage_TX2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1)
#define minidrone_MinidroneMessage_TX2_CALLBACK NULL
#define minidrone_MinidroneMessage_TX2_DEFAULT NULL

extern const pb_msgdesc_t minidrone_MinidroneMessage_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_QDES_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_QDES_ComputeUnit_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_QDES_BatteryUnit_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_DriveTrain_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_DriveTrain_Servo_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_DriveTrain_Wheels_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_DriveTrain_Wheels_Left_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_DriveTrain_Wheels_Right_msg;
extern const pb_msgdesc_t minidrone_MinidroneMessage_TX2_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define minidrone_MinidroneMessage_fields &minidrone_MinidroneMessage_msg
#define minidrone_MinidroneMessage_QDES_fields &minidrone_MinidroneMessage_QDES_msg
#define minidrone_MinidroneMessage_QDES_ComputeUnit_fields &minidrone_MinidroneMessage_QDES_ComputeUnit_msg
#define minidrone_MinidroneMessage_QDES_BatteryUnit_fields &minidrone_MinidroneMessage_QDES_BatteryUnit_msg
#define minidrone_MinidroneMessage_DriveTrain_fields &minidrone_MinidroneMessage_DriveTrain_msg
#define minidrone_MinidroneMessage_DriveTrain_Servo_fields &minidrone_MinidroneMessage_DriveTrain_Servo_msg
#define minidrone_MinidroneMessage_DriveTrain_Wheels_fields &minidrone_MinidroneMessage_DriveTrain_Wheels_msg
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Left_fields &minidrone_MinidroneMessage_DriveTrain_Wheels_Left_msg
#define minidrone_MinidroneMessage_DriveTrain_Wheels_Right_fields &minidrone_MinidroneMessage_DriveTrain_Wheels_Right_msg
#define minidrone_MinidroneMessage_TX2_fields &minidrone_MinidroneMessage_TX2_msg

/* Maximum encoded size of messages (where known) */
/* minidrone_MinidroneMessage_DriveTrain_Wheels_Left_size depends on runtime parameters */
/* minidrone_MinidroneMessage_DriveTrain_Wheels_Right_size depends on runtime parameters */
#define minidrone_MinidroneMessage_DriveTrain_Servo_size 5
#define minidrone_MinidroneMessage_DriveTrain_Wheels_size 0
#define minidrone_MinidroneMessage_DriveTrain_size 0
#define minidrone_MinidroneMessage_QDES_BatteryUnit_size 15
#define minidrone_MinidroneMessage_QDES_ComputeUnit_size 10
#define minidrone_MinidroneMessage_QDES_size     0
#define minidrone_MinidroneMessage_TX2_size      5
#define minidrone_MinidroneMessage_size          0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
