/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "minidrone.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(minidrone_Test, minidrone_Test, AUTO)


PB_BIND(minidrone_MinidroneMessage, minidrone_MinidroneMessage, AUTO)



