/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_MINIDRONE_I2C_ARDUINO_LIBRARIES_PROTO_MINIDRONE_PB_H_INCLUDED
#define PB_MINIDRONE_I2C_ARDUINO_LIBRARIES_PROTO_MINIDRONE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _minidrone_TX2 {
    float temp;
} minidrone_TX2;

typedef struct _minidrone_ComputeUnit {
    float temp;
    int32_t fan_speed;
    bool has_tx2;
    minidrone_TX2 tx2;
} minidrone_ComputeUnit;

typedef struct _minidrone_BatteryUnit {
    float temp;
    float fan_speed;
    float voltage;
} minidrone_BatteryUnit;

typedef struct _minidrone_QDES {
    bool has_computeUnit;
    minidrone_ComputeUnit computeUnit;
    bool has_batteryUnit;
    minidrone_BatteryUnit batteryUnit;
} minidrone_QDES;

typedef struct _minidrone_Servo {
    float angle;
} minidrone_Servo;

typedef struct _minidrone_LeftWheel {
    float speed;
    pb_callback_t direction;
} minidrone_LeftWheel;

typedef struct _minidrone_RightWheel {
    float speed;
    pb_callback_t direction;
} minidrone_RightWheel;

typedef struct _minidrone_Wheels {
    bool has_left;
    minidrone_LeftWheel left;
    bool has_right;
    minidrone_RightWheel right;
} minidrone_Wheels;

typedef struct _minidrone_DriveTrain {
    bool has_servo;
    minidrone_Servo servo;
    bool has_wheels;
    minidrone_Wheels wheels;
} minidrone_DriveTrain;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define minidrone_TX2_init_default               {0}
#define minidrone_ComputeUnit_init_default       {0, 0, false, minidrone_TX2_init_default}
#define minidrone_BatteryUnit_init_default       {0, 0, 0}
#define minidrone_QDES_init_default              {false, minidrone_ComputeUnit_init_default, false, minidrone_BatteryUnit_init_default}
#define minidrone_Servo_init_default             {0}
#define minidrone_LeftWheel_init_default         {0, {{NULL}, NULL}}
#define minidrone_RightWheel_init_default        {0, {{NULL}, NULL}}
#define minidrone_Wheels_init_default            {false, minidrone_LeftWheel_init_default, false, minidrone_RightWheel_init_default}
#define minidrone_DriveTrain_init_default        {false, minidrone_Servo_init_default, false, minidrone_Wheels_init_default}
#define minidrone_TX2_init_zero                  {0}
#define minidrone_ComputeUnit_init_zero          {0, 0, false, minidrone_TX2_init_zero}
#define minidrone_BatteryUnit_init_zero          {0, 0, 0}
#define minidrone_QDES_init_zero                 {false, minidrone_ComputeUnit_init_zero, false, minidrone_BatteryUnit_init_zero}
#define minidrone_Servo_init_zero                {0}
#define minidrone_LeftWheel_init_zero            {0, {{NULL}, NULL}}
#define minidrone_RightWheel_init_zero           {0, {{NULL}, NULL}}
#define minidrone_Wheels_init_zero               {false, minidrone_LeftWheel_init_zero, false, minidrone_RightWheel_init_zero}
#define minidrone_DriveTrain_init_zero           {false, minidrone_Servo_init_zero, false, minidrone_Wheels_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define minidrone_TX2_temp_tag                   1
#define minidrone_ComputeUnit_temp_tag           1
#define minidrone_ComputeUnit_fan_speed_tag      2
#define minidrone_ComputeUnit_tx2_tag            3
#define minidrone_BatteryUnit_temp_tag           1
#define minidrone_BatteryUnit_fan_speed_tag      2
#define minidrone_BatteryUnit_voltage_tag        3
#define minidrone_QDES_computeUnit_tag           1
#define minidrone_QDES_batteryUnit_tag           2
#define minidrone_Servo_angle_tag                1
#define minidrone_LeftWheel_speed_tag            1
#define minidrone_LeftWheel_direction_tag        2
#define minidrone_RightWheel_speed_tag           1
#define minidrone_RightWheel_direction_tag       2
#define minidrone_Wheels_left_tag                1
#define minidrone_Wheels_right_tag               2
#define minidrone_DriveTrain_servo_tag           1
#define minidrone_DriveTrain_wheels_tag          2

/* Struct field encoding specification for nanopb */
#define minidrone_TX2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1)
#define minidrone_TX2_CALLBACK NULL
#define minidrone_TX2_DEFAULT NULL

#define minidrone_ComputeUnit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1) \
X(a, STATIC,   SINGULAR, INT32,    fan_speed,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tx2,               3)
#define minidrone_ComputeUnit_CALLBACK NULL
#define minidrone_ComputeUnit_DEFAULT NULL
#define minidrone_ComputeUnit_tx2_MSGTYPE minidrone_TX2

#define minidrone_BatteryUnit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    fan_speed,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           3)
#define minidrone_BatteryUnit_CALLBACK NULL
#define minidrone_BatteryUnit_DEFAULT NULL

#define minidrone_QDES_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  computeUnit,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  batteryUnit,       2)
#define minidrone_QDES_CALLBACK NULL
#define minidrone_QDES_DEFAULT NULL
#define minidrone_QDES_computeUnit_MSGTYPE minidrone_ComputeUnit
#define minidrone_QDES_batteryUnit_MSGTYPE minidrone_BatteryUnit

#define minidrone_Servo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             1)
#define minidrone_Servo_CALLBACK NULL
#define minidrone_Servo_DEFAULT NULL

#define minidrone_LeftWheel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, CALLBACK, SINGULAR, STRING,   direction,         2)
#define minidrone_LeftWheel_CALLBACK pb_default_field_callback
#define minidrone_LeftWheel_DEFAULT NULL

#define minidrone_RightWheel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, CALLBACK, SINGULAR, STRING,   direction,         2)
#define minidrone_RightWheel_CALLBACK pb_default_field_callback
#define minidrone_RightWheel_DEFAULT NULL

#define minidrone_Wheels_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  left,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  right,             2)
#define minidrone_Wheels_CALLBACK NULL
#define minidrone_Wheels_DEFAULT NULL
#define minidrone_Wheels_left_MSGTYPE minidrone_LeftWheel
#define minidrone_Wheels_right_MSGTYPE minidrone_RightWheel

#define minidrone_DriveTrain_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  servo,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wheels,            2)
#define minidrone_DriveTrain_CALLBACK NULL
#define minidrone_DriveTrain_DEFAULT NULL
#define minidrone_DriveTrain_servo_MSGTYPE minidrone_Servo
#define minidrone_DriveTrain_wheels_MSGTYPE minidrone_Wheels

extern const pb_msgdesc_t minidrone_TX2_msg;
extern const pb_msgdesc_t minidrone_ComputeUnit_msg;
extern const pb_msgdesc_t minidrone_BatteryUnit_msg;
extern const pb_msgdesc_t minidrone_QDES_msg;
extern const pb_msgdesc_t minidrone_Servo_msg;
extern const pb_msgdesc_t minidrone_LeftWheel_msg;
extern const pb_msgdesc_t minidrone_RightWheel_msg;
extern const pb_msgdesc_t minidrone_Wheels_msg;
extern const pb_msgdesc_t minidrone_DriveTrain_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define minidrone_TX2_fields &minidrone_TX2_msg
#define minidrone_ComputeUnit_fields &minidrone_ComputeUnit_msg
#define minidrone_BatteryUnit_fields &minidrone_BatteryUnit_msg
#define minidrone_QDES_fields &minidrone_QDES_msg
#define minidrone_Servo_fields &minidrone_Servo_msg
#define minidrone_LeftWheel_fields &minidrone_LeftWheel_msg
#define minidrone_RightWheel_fields &minidrone_RightWheel_msg
#define minidrone_Wheels_fields &minidrone_Wheels_msg
#define minidrone_DriveTrain_fields &minidrone_DriveTrain_msg

/* Maximum encoded size of messages (where known) */
/* minidrone_LeftWheel_size depends on runtime parameters */
/* minidrone_RightWheel_size depends on runtime parameters */
/* minidrone_Wheels_size depends on runtime parameters */
/* minidrone_DriveTrain_size depends on runtime parameters */
#define minidrone_BatteryUnit_size               15
#define minidrone_ComputeUnit_size               23
#define minidrone_QDES_size                      42
#define minidrone_Servo_size                     5
#define minidrone_TX2_size                       5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
