/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "minidrone.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(minidrone_MinidroneMessage, minidrone_MinidroneMessage, AUTO)


PB_BIND(minidrone_MinidroneMessage_QDES, minidrone_MinidroneMessage_QDES, AUTO)


PB_BIND(minidrone_MinidroneMessage_QDES_ComputeUnit, minidrone_MinidroneMessage_QDES_ComputeUnit, AUTO)


PB_BIND(minidrone_MinidroneMessage_QDES_BatteryUnit, minidrone_MinidroneMessage_QDES_BatteryUnit, AUTO)


PB_BIND(minidrone_MinidroneMessage_DriveTrain, minidrone_MinidroneMessage_DriveTrain, AUTO)


PB_BIND(minidrone_MinidroneMessage_DriveTrain_Servo, minidrone_MinidroneMessage_DriveTrain_Servo, AUTO)


PB_BIND(minidrone_MinidroneMessage_DriveTrain_Wheels, minidrone_MinidroneMessage_DriveTrain_Wheels, AUTO)


PB_BIND(minidrone_MinidroneMessage_DriveTrain_Wheels_Left, minidrone_MinidroneMessage_DriveTrain_Wheels_Left, AUTO)


PB_BIND(minidrone_MinidroneMessage_DriveTrain_Wheels_Right, minidrone_MinidroneMessage_DriveTrain_Wheels_Right, AUTO)


PB_BIND(minidrone_MinidroneMessage_TX2, minidrone_MinidroneMessage_TX2, AUTO)



